---
#
# roles/java/tasks/main.yml
#

- name: get oracle JDK
  shell: 'wget --no-cookies --no-check-certificate --header "Cookie: oraclelicense=accept-securebackup-cookie" "{{ java.get_url }}/{{ java.get_rpm }}"'
  args:
    chdir: /var/tmp

- name: install java from rpm
  shell: rpm -ivh {{ java.get_rpm }}
  args:
    chdir:  /var/tmp
